#DUBBO
dubbox:
  application:
    name: dw-home-web-sso
    organization: dubbox
    owner: dw
  registry:
    protocol: zookeeper
    address: 192.168.125.128:2181
  annotation:
    package: com.home.sso.controller
  monitor:
    enabled: false
    address: 192.168.125.1:6060
    username: admin
    password: admin

#配置模板想到classpath路径，后面须加上"/"
beetl:
  templates-path: templates/
  config:
      html-tag-flag: true
#配置模板的后缀，自动读取spring.mvc.view.suffix
spring:
  mvc:
    view:
      suffix: .html

server:
  port: 8103


# swagger2
swagger2.package: cn.binux.item.controller

